[DEC30_3]

DROP TABLE MARKET;
DROP SEQUENCE MARKET_SEQ;
CREATE TABLE MARKET(
    M_NO NUMBER(4) PRIMARY KEY,
    M_NAME VARCHAR2(10 CHAR) NOT NULL,
    M_LOCATION VARCHAR2(10 CHAR) NOT NULL,
    M_LAND NUMBER(4) NOT NULL,      -- 그 매장의 평수
    M_PARKING NUMBER(4) NOT NULL    -- 주차 가능한 대수
);

CREATE SEQUENCE MARKET_SEQ;
INSERT INTO MARKET VALUES(MARKET_SEQ.NEXTVAL, '홈플러스', '강남', 1000, 500);
INSERT INTO MARKET VALUES(MARKET_SEQ.NEXTVAL, '홈플러스', '부천', 500, 300);
INSERT INTO MARKET VALUES(MARKET_SEQ.NEXTVAL, '이마트', '서초', 800, 800);
--------------------------------------------------------------------------------
DROP TABLE PRODUCT;
DROP SEQUENCE PRODUCT_SEQ;
CREATE TABLE PRODUCT(
    P_NO VARCHAR2(10 CHAR) PRIMARY KEY,
    P_NAME VARCHAR2(10 CHAR) NOT NULL,
    P_WEIGHT NUMBER(4) NOT NULL,
    P_PRICE NUMBER(5) NOT NULL,
    P_M_NO NUMBER(4) NOT NULL,
    CONSTRAINT FK_P_M_NO FOREIGN KEY(P_M_NO)
    REFERENCES MARKET(M_NO)
    ON DELETE CASCADE
);

CREATE SEQUENCE PRODUCT_SEQ;

INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL, '배추', 3000, 10000, 1);
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL, '무', 500, 5000, 2);
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL, '배추', 2000, 5000, 3);

-- U(UPDATAE)
UPDATE [테이블명]
SET 필드명 = 값, 필드명 = 값, ... -- 바꿀 내용
WHERE 조건;
-- 홈플러스 부천점의 상품 가격 10% 할인
UPDATE PRODUCT
    SET P_PRICE = P_PRICE * 0.9
        WHERE P_M_NO IN (
            SELECT M_NO
            FROM MARKET
            WHERE M_NAME = '홈플러스' AND M_LOCATION = '부천'
        );

-- 제일 비싼거 10%할인
UPDATE PRODUCT
    SET P_PRICE = P_PRICE * 0.9
        WHERE  P_PRICE = (
        SELECT MAX(P_PRICE)
        FROM PRODUCT
    );
------------------------------------
-- D(DELETE)
DELETE FROM [테이블명]
WHERE 조건식;
-- 가장 좁은 매장 상품 다 삭제
DELETE FROM PRODUCT
    WHERE P_M_NO IN (
        SELECT M_NO
        FROM MARKET
        WHERE M_LAND IN (
            SELECT MIN(M_LAND)
            FROM MARKET
        )
    );
SELECT * FROM MARKET;
SELECT * FROM PRODUCT;




